export default [
    {
      name: 'スプラシューター ',
      id: 92,
      subWeaponId: 13,
      specialWeaponId: 11,
    },
    {
      name: 'スプラシューターコラボ ',
      id: 105,
      subWeaponId: 11,
      specialWeaponId: 10,
    },
    {
      name: 'ヒーローシューター レプリカ ',
      id: 132,
      subWeaponId: 13,
      specialWeaponId: 11,
    },
    {
      name: 'オクタシューター レプリカ ',
      id: 189,
      subWeaponId: 11,
      specialWeaponId: 10,
    },
    {
      name: 'スプラシューターベッチュー ',
      id: 198,
      subWeaponId: 12,
      specialWeaponId: 8,
    },
    {
      name: 'プライムシューター ',
      id: 100,
      subWeaponId: 18,
      specialWeaponId: 14,
    },
    {
      name: 'プライムシューターコラボ ',
      id: 145,
      subWeaponId: 12,
      specialWeaponId: 16,
    },
    {
      name: 'プライムシューターベッチュー ',
      id: 203,
      subWeaponId: 11,
      specialWeaponId: 22,
    },
    {
      name: 'シャープマーカー ',
      id: 102,
      subWeaponId: 17,
      specialWeaponId: 10,
    },
    {
      name: 'シャープマーカーネオ ',
      id: 181,
      subWeaponId: 13,
      specialWeaponId: 18,
    },
    {
      name: 'わかばシューター ',
      id: 104,
      subWeaponId: 11,
      specialWeaponId: 12,
    },
    {
      name: 'もみじシューター ',
      id: 146,
      subWeaponId: 15,
      specialWeaponId: 14,
    },
    {
      name: 'おちばシューター ',
      id: 207,
      subWeaponId: 23,
      specialWeaponId: 16,
    },
    {
      name: 'プロモデラーMG ',
      id: 106,
      subWeaponId: 12,
      specialWeaponId: 19,
    },
    {
      name: 'プロモデラーRG ',
      id: 126,
      subWeaponId: 20,
      specialWeaponId: 15,
    },
    {
      name: 'プロモデラーPG ',
      id: 220,
      subWeaponId: 13,
      specialWeaponId: 22,
    },
    {
      name: 'N-ZAP85 ',
      id: 108,
      subWeaponId: 12,
      specialWeaponId: 12,
    },
    {
      name: 'N-ZAP89 ',
      id: 160,
      subWeaponId: 15,
      specialWeaponId: 8,
    },
    {
      name: 'N-ZAP83 ',
      id: 221,
      subWeaponId: 20,
      specialWeaponId: 14,
    },
    {
      name: '.52ガロン ',
      id: 112,
      subWeaponId: 18,
      specialWeaponId: 15,
    },
    {
      name: '.52ガロンデコ ',
      id: 167,
      subWeaponId: 14,
      specialWeaponId: 9,
    },
    {
      name: '.52ガロンベッチュー ',
      id: 211,
      subWeaponId: 19,
      specialWeaponId: 22,
    },
    {
      name: 'ジェットスイーパー ',
      id: 115,
      subWeaponId: 17,
      specialWeaponId: 8,
    },
    {
      name: 'ジェットスイーパーカスタム ',
      id: 155,
      subWeaponId: 13,
      specialWeaponId: 9,
    },
    {
      name: 'L3リールガン ',
      id: 116,
      subWeaponId: 14,
      specialWeaponId: 15,
    },
    {
      name: 'L3リールガンD ',
      id: 165,
      subWeaponId: 13,
      specialWeaponId: 10,
    },
    {
      name: 'L3リールガンベッチュー ',
      id: 208,
      subWeaponId: 19,
      specialWeaponId: 23,
    },
    {
      name: '.96ガロン ',
      id: 119,
      subWeaponId: 20,
      specialWeaponId: 12,
    },
    {
      name: '.96ガロンデコ ',
      id: 169,
      subWeaponId: 19,
      specialWeaponId: 11,
    },
    {
      name: 'H3リールガン ',
      id: 127,
      subWeaponId: 18,
      specialWeaponId: 8,
    },
    {
      name: 'H3リールガンD ',
      id: 175,
      subWeaponId: 12,
      specialWeaponId: 12,
    },
    {
      name: 'H3リールガンチェリー ',
      id: 223,
      subWeaponId: 19,
      specialWeaponId: 16,
    },
    {
      name: 'ボールドマーカー ',
      id: 140,
      subWeaponId: 14,
      specialWeaponId: 11,
    },
    {
      name: 'ボールドマーカーネオ ',
      id: 174,
      subWeaponId: 21,
      specialWeaponId: 8,
    },
    {
      name: 'ボールドマーカー7 ',
      id: 219,
      subWeaponId: 11,
      specialWeaponId: 23,
    },
    {
      name: 'ボトルガイザー ',
      id: 162,
      subWeaponId: 19,
      specialWeaponId: 9,
    },
    {
      name: 'ボトルガイザーフォイル ',
      id: 182,
      subWeaponId: 11,
      specialWeaponId: 16,
    },
    {
      name: 'ホットブラスター ',
      id: 98,
      subWeaponId: 17,
      specialWeaponId: 11,
    },
    {
      name: 'ホットブラスターカスタム ',
      id: 125,
      subWeaponId: 15,
      specialWeaponId: 10,
    },
    {
      name: 'ヒーローブラスター レプリカ ',
      id: 136,
      subWeaponId: 17,
      specialWeaponId: 11,
    },
    {
      name: 'ラピッドブラスター ',
      id: 111,
      subWeaponId: 16,
      specialWeaponId: 17,
    },
    {
      name: 'ラピッドブラスターデコ ',
      id: 168,
      subWeaponId: 12,
      specialWeaponId: 10,
    },
    {
      name: 'ラピッドブラスターベッチュー ',
      id: 212,
      subWeaponId: 23,
      specialWeaponId: 15,
    },
    {
      name: 'ノヴァブラスター ',
      id: 117,
      subWeaponId: 11,
      specialWeaponId: 15,
    },
    {
      name: 'ノヴァブラスターネオ ',
      id: 172,
      subWeaponId: 16,
      specialWeaponId: 18,
    },
    {
      name: 'ノヴァブラスターベッチュー ',
      id: 204,
      subWeaponId: 22,
      specialWeaponId: 14,
    },
    {
      name: 'クラッシュブラスター ',
      id: 128,
      subWeaponId: 11,
      specialWeaponId: 9,
    },
    {
      name: 'クラッシュブラスターネオ ',
      id: 178,
      subWeaponId: 14,
      specialWeaponId: 8,
    },
    {
      name: 'Rブラスターエリート ',
      id: 148,
      subWeaponId: 17,
      specialWeaponId: 14,
    },
    {
      name: 'Rブラスターエリートデコ ',
      id: 185,
      subWeaponId: 19,
      specialWeaponId: 12,
    },
    {
      name: 'ロングブラスター ',
      id: 153,
      subWeaponId: 12,
      specialWeaponId: 14,
    },
    {
      name: 'ロングブラスターカスタム ',
      id: 180,
      subWeaponId: 14,
      specialWeaponId: 16,
    },
    {
      name: 'ロングブラスターネクロ ',
      id: 222,
      subWeaponId: 13,
      specialWeaponId: 8,
    },
    {
      name: 'スプラローラー ',
      id: 93,
      subWeaponId: 14,
      specialWeaponId: 11,
    },
    {
      name: 'スプラローラーコラボ ',
      id: 110,
      subWeaponId: 21,
      specialWeaponId: 15,
    },
    {
      name: 'ヒーローローラー レプリカ ',
      id: 133,
      subWeaponId: 14,
      specialWeaponId: 11,
    },
    {
      name: 'スプラローラーベッチュー ',
      id: 199,
      subWeaponId: 11,
      specialWeaponId: 16,
    },
    {
      name: 'ダイナモローラー ',
      id: 101,
      subWeaponId: 16,
      specialWeaponId: 9,
    },
    {
      name: 'ダイナモローラーテスラ ',
      id: 154,
      subWeaponId: 11,
      specialWeaponId: 12,
    },
    {
      name: 'ダイナモローラーベッチュー ',
      id: 205,
      subWeaponId: 20,
      specialWeaponId: 22,
    },
    {
      name: 'カーボンローラー ',
      id: 107,
      subWeaponId: 15,
      specialWeaponId: 14,
    },
    {
      name: 'カーボンローラーデコ ',
      id: 186,
      subWeaponId: 13,
      specialWeaponId: 20,
    },
    {
      name: 'ヴァリアブルローラー ',
      id: 122,
      subWeaponId: 19,
      specialWeaponId: 17,
    },
    {
      name: 'ヴァリアブルローラーフォイル ',
      id: 157,
      subWeaponId: 12,
      specialWeaponId: 8,
    },
    {
      name: 'ホクサイ ',
      id: 99,
      subWeaponId: 15,
      specialWeaponId: 10,
    },
    {
      name: 'ヒーローブラシ レプリカ ',
      id: 139,
      subWeaponId: 15,
      specialWeaponId: 10,
    },
    {
      name: 'ホクサイ・ヒュー ',
      id: 164,
      subWeaponId: 21,
      specialWeaponId: 8,
    },
    {
      name: 'ホクサイベッチュー ',
      id: 209,
      subWeaponId: 12,
      specialWeaponId: 23,
    },
    {
      name: 'パブロ ',
      id: 130,
      subWeaponId: 11,
      specialWeaponId: 11,
    },
    {
      name: 'パブロ・ヒュー ',
      id: 156,
      subWeaponId: 16,
      specialWeaponId: 15,
    },
    {
      name: 'パーマネント・パブロ ',
      id: 224,
      subWeaponId: 20,
      specialWeaponId: 12,
    },
    {
      name: 'スプラチャージャー ',
      id: 94,
      subWeaponId: 11,
      specialWeaponId: 9,
    },
    {
      name: 'スプラスコープ ',
      id: 103,
      subWeaponId: 11,
      specialWeaponId: 9,
    },
    {
      name: 'スプラチャージャーコラボ ',
      id: 114,
      subWeaponId: 19,
      specialWeaponId: 18,
    },
    {
      name: 'スプラスコープコラボ ',
      id: 123,
      subWeaponId: 19,
      specialWeaponId: 18,
    },
    {
      name: 'ヒーローチャージャー レプリカ ',
      id: 134,
      subWeaponId: 11,
      specialWeaponId: 9,
    },
    {
      name: 'スプラチャージャーベッチュー ',
      id: 200,
      subWeaponId: 20,
      specialWeaponId: 15,
    },
    {
      name: 'スプラスコープベッチュー ',
      id: 201,
      subWeaponId: 20,
      specialWeaponId: 15,
    },
    {
      name: 'リッター4K ',
      id: 118,
      subWeaponId: 16,
      specialWeaponId: 14,
    },
    {
      name: '4Kスコープ ',
      id: 129,
      subWeaponId: 16,
      specialWeaponId: 14,
    },
    {
      name: 'リッター4Kカスタム ',
      id: 151,
      subWeaponId: 21,
      specialWeaponId: 16,
    },
    {
      name: '4Kスコープカスタム ',
      id: 152,
      subWeaponId: 21,
      specialWeaponId: 16,
    },
    {
      name: 'ソイチューバー ',
      id: 120,
      subWeaponId: 12,
      specialWeaponId: 11,
    },
    {
      name: 'ソイチューバーカスタム ',
      id: 170,
      subWeaponId: 14,
      specialWeaponId: 10,
    },
    {
      name: 'スクイックリンα ',
      id: 143,
      subWeaponId: 18,
      specialWeaponId: 12,
    },
    {
      name: 'スクイックリンβ ',
      id: 183,
      subWeaponId: 15,
      specialWeaponId: 15,
    },
    {
      name: 'スクイックリンγ ',
      id: 225,
      subWeaponId: 12,
      specialWeaponId: 10,
    },
    {
      name: '14式竹筒銃・甲 ',
      id: 150,
      subWeaponId: 14,
      specialWeaponId: 8,
    },
    {
      name: '14式竹筒銃・乙 ',
      id: 190,
      subWeaponId: 17,
      specialWeaponId: 21,
    },
    {
      name: '14式竹筒銃・丙 ',
      id: 226,
      subWeaponId: 22,
      specialWeaponId: 16,
    },
    {
      name: 'バケットスロッシャー ',
      id: 96,
      subWeaponId: 12,
      specialWeaponId: 8,
    },
    {
      name: 'ヒーロースロッシャー レプリカ ',
      id: 137,
      subWeaponId: 12,
      specialWeaponId: 8,
    },
    {
      name: 'バケットスロッシャーデコ ',
      id: 161,
      subWeaponId: 20,
      specialWeaponId: 15,
    },
    {
      name: 'バケットスロッシャーソーダ ',
      id: 227,
      subWeaponId: 11,
      specialWeaponId: 13,
    },
    {
      name: 'ヒッセン ',
      id: 113,
      subWeaponId: 13,
      specialWeaponId: 12,
    },
    {
      name: 'ヒッセン・ヒュー ',
      id: 179,
      subWeaponId: 11,
      specialWeaponId: 14,
    },
    {
      name: 'スクリュースロッシャー ',
      id: 144,
      subWeaponId: 15,
      specialWeaponId: 9,
    },
    {
      name: 'スクリュースロッシャーネオ ',
      id: 171,
      subWeaponId: 18,
      specialWeaponId: 17,
    },
    {
      name: 'スクリュースロッシャーベッチュー ',
      id: 206,
      subWeaponId: 22,
      specialWeaponId: 11,
    },
    {
      name: 'エクスプロッシャー ',
      id: 191,
      subWeaponId: 20,
      specialWeaponId: 16,
    },
    {
      name: 'エクスプロッシャーカスタム ',
      id: 214,
      subWeaponId: 18,
      specialWeaponId: 15,
    },
    {
      name: 'オーバーフロッシャー ',
      id: 194,
      subWeaponId: 19,
      specialWeaponId: 14,
    },
    {
      name: 'オーバーフロッシャーデコ ',
      id: 213,
      subWeaponId: 20,
      specialWeaponId: 18,
    },
    {
      name: 'バレルスピナー ',
      id: 97,
      subWeaponId: 20,
      specialWeaponId: 9,
    },
    {
      name: 'ヒーロースピナー レプリカ ',
      id: 138,
      subWeaponId: 20,
      specialWeaponId: 9,
    },
    {
      name: 'バレルスピナーデコ ',
      id: 147,
      subWeaponId: 19,
      specialWeaponId: 16,
    },
    {
      name: 'バレルスピナーリミックス ',
      id: 228,
      subWeaponId: 18,
      specialWeaponId: 22,
    },
    {
      name: 'スプラスピナー ',
      id: 121,
      subWeaponId: 13,
      specialWeaponId: 8,
    },
    {
      name: 'スプラスピナーコラボ ',
      id: 176,
      subWeaponId: 14,
      specialWeaponId: 14,
    },
    {
      name: 'スプラスピナーベッチュー ',
      id: 215,
      subWeaponId: 17,
      specialWeaponId: 23,
    },
    {
      name: 'ハイドラント ',
      id: 158,
      subWeaponId: 15,
      specialWeaponId: 11,
    },
    {
      name: 'ハイドラントカスタム ',
      id: 195,
      subWeaponId: 16,
      specialWeaponId: 12,
    },
    {
      name: 'クーゲルシュライバー ',
      id: 192,
      subWeaponId: 17,
      specialWeaponId: 10,
    },
    {
      name: 'クーゲルシュライバー・ヒュー ',
      id: 216,
      subWeaponId: 21,
      specialWeaponId: 14,
    },
    {
      name: 'ノーチラス47 ',
      id: 196,
      subWeaponId: 18,
      specialWeaponId: 15,
    },
    {
      name: 'ノーチラス79 ',
      id: 217,
      subWeaponId: 12,
      specialWeaponId: 10,
    },
    {
      name: 'スプラマニューバー ',
      id: 95,
      subWeaponId: 13,
      specialWeaponId: 8,
    },
    {
      name: 'スプラマニューバーコラボ ',
      id: 109,
      subWeaponId: 14,
      specialWeaponId: 10,
    },
    {
      name: 'ヒーローマニューバー レプリカ ',
      id: 135,
      subWeaponId: 13,
      specialWeaponId: 8,
    },
    {
      name: 'スプラマニューバーベッチュー ',
      id: 202,
      subWeaponId: 12,
      specialWeaponId: 15,
    },
    {
      name: 'スパッタリー ',
      id: 124,
      subWeaponId: 21,
      specialWeaponId: 18,
    },
    {
      name: 'スパッタリー・ヒュー ',
      id: 166,
      subWeaponId: 17,
      specialWeaponId: 14,
    },
    {
      name: 'スパッタリークリア ',
      id: 229,
      subWeaponId: 23,
      specialWeaponId: 11,
    },
    {
      name: 'デュアルスイーパー ',
      id: 131,
      subWeaponId: 18,
      specialWeaponId: 8,
    },
    {
      name: 'デュアルスイーパーカスタム ',
      id: 187,
      subWeaponId: 11,
      specialWeaponId: 14,
    },
    {
      name: 'ケルビン525 ',
      id: 159,
      subWeaponId: 16,
      specialWeaponId: 10,
    },
    {
      name: 'ケルビン525デコ ',
      id: 184,
      subWeaponId: 19,
      specialWeaponId: 15,
    },
    {
      name: 'ケルビン525ベッチュー ',
      id: 218,
      subWeaponId: 22,
      specialWeaponId: 12,
    },
    {
      name: 'クアッドホッパーブラック ',
      id: 173,
      subWeaponId: 15,
      specialWeaponId: 11,
    },
    {
      name: 'クアッドホッパーホワイト ',
      id: 197,
      subWeaponId: 20,
      specialWeaponId: 20,
    },
    {
      name: 'パラシェルター ',
      id: 141,
      subWeaponId: 20,
      specialWeaponId: 14,
    },
    {
      name: 'ヒーローシェルター レプリカ ',
      id: 142,
      subWeaponId: 20,
      specialWeaponId: 14,
    },
    {
      name: 'パラシェルターソレーラ ',
      id: 177,
      subWeaponId: 15,
      specialWeaponId: 17,
    },
    {
      name: 'キャンピングシェルター ',
      id: 149,
      subWeaponId: 21,
      specialWeaponId: 16,
    },
    {
      name: 'キャンピングシェルターソレーラ ',
      id: 193,
      subWeaponId: 19,
      specialWeaponId: 19,
    },
    {
      name: 'キャンピングシェルターカーモ ',
      id: 230,
      subWeaponId: 16,
      specialWeaponId: 23,
    },
    {
      name: 'スパイガジェット ',
      id: 163,
      subWeaponId: 16,
      specialWeaponId: 11,
    },
    {
      name: 'スパイガジェットソレーラ ',
      id: 188,
      subWeaponId: 11,
      specialWeaponId: 15,
    },
    {
      name: 'スパイガジェットベッチュー ',
      id: 210,
      subWeaponId: 23,
      specialWeaponId: 12,
    },
];
