export default [
    {
      name: 'スプラシューター ',
      name_en: 'Splattershot ',
      id: 92,
      subWeaponId: 13,
      specialWeaponId: 11,
    },
    {
      name: 'スプラシューターコラボ ',
      name_en: 'Tentatek Splattershot ',
      id: 105,
      subWeaponId: 11,
      specialWeaponId: 10,
    },
    {
      name: 'ヒーローシューター レプリカ ',
      name_en: 'Hero Shot Replica ',
      id: 132,
      subWeaponId: 13,
      specialWeaponId: 11,
    },
    {
      name: 'オクタシューター レプリカ ',
      name_en: 'Octo Shot Replica ',
      id: 189,
      subWeaponId: 11,
      specialWeaponId: 10,
    },
    {
      name: 'スプラシューターベッチュー ',
      name_en: 'Kensa Splattershot ',
      id: 198,
      subWeaponId: 12,
      specialWeaponId: 8,
    },
    {
      name: 'プライムシューター ',
      name_en: 'Splattershot Pro ',
      id: 100,
      subWeaponId: 18,
      specialWeaponId: 14,
    },
    {
      name: 'プライムシューターコラボ ',
      name_en: 'Forge Splattershot Pro ',
      id: 145,
      subWeaponId: 12,
      specialWeaponId: 16,
    },
    {
      name: 'プライムシューターベッチュー ',
      name_en: 'Kensa Splattershot Pro ',
      id: 203,
      subWeaponId: 11,
      specialWeaponId: 22,
    },
    {
      name: 'シャープマーカー ',
      name_en: 'Splash-o-matic ',
      id: 102,
      subWeaponId: 17,
      specialWeaponId: 10,
    },
    {
      name: 'シャープマーカーネオ ',
      name_en: 'Neo Splash-o-matic ',
      id: 181,
      subWeaponId: 13,
      specialWeaponId: 18,
    },
    {
      name: 'わかばシューター ',
      name_en: 'Splattershot Jr. ',
      id: 104,
      subWeaponId: 11,
      specialWeaponId: 12,
    },
    {
      name: 'もみじシューター ',
      name_en: 'Custom Splattershot Jr. ',
      id: 146,
      subWeaponId: 15,
      specialWeaponId: 14,
    },
    {
      name: 'おちばシューター ',
      name_en: 'Kensa Splattershot Jr. ',
      id: 207,
      subWeaponId: 23,
      specialWeaponId: 16,
    },
    {
      name: 'プロモデラーMG ',
      name_en: 'Aerospray MG ',
      id: 106,
      subWeaponId: 12,
      specialWeaponId: 19,
    },
    {
      name: 'プロモデラーRG ',
      name_en: 'Aerospray RG ',
      id: 126,
      subWeaponId: 20,
      specialWeaponId: 15,
    },
    {
      name: 'プロモデラーPG ',
      name_en: 'TBC ',
      id: 220,
      subWeaponId: 13,
      specialWeaponId: 22,
    },
    {
      name: 'N-ZAP85 ',
      name_en: 'N-ZAP \'85 ',
      id: 108,
      subWeaponId: 12,
      specialWeaponId: 12,
    },
    {
      name: 'N-ZAP89 ',
      name_en: 'N-ZAP \'89 ',
      id: 160,
      subWeaponId: 15,
      specialWeaponId: 8,
    },
    {
      name: 'N-ZAP83 ',
      name_en: 'TBC ',
      id: 221,
      subWeaponId: 20,
      specialWeaponId: 14,
    },
    {
      name: '.52ガロン ',
      name_en: '.52 Gal ',
      id: 112,
      subWeaponId: 18,
      specialWeaponId: 15,
    },
    {
      name: '.52ガロンデコ ',
      name_en: '.52 Gal Deco ',
      id: 167,
      subWeaponId: 14,
      specialWeaponId: 9,
    },
    {
      name: '.52ガロンベッチュー ',
      name_en: 'Kensa .52 Gal ',
      id: 211,
      subWeaponId: 19,
      specialWeaponId: 22,
    },
    {
      name: 'ジェットスイーパー ',
      name_en: 'Jet Squelcher ',
      id: 115,
      subWeaponId: 17,
      specialWeaponId: 8,
    },
    {
      name: 'ジェットスイーパーカスタム ',
      name_en: 'Custom Jet Squelcher ',
      id: 155,
      subWeaponId: 13,
      specialWeaponId: 9,
    },
    {
      name: 'L3リールガン ',
      name_en: 'L-3 Nozzlenose ',
      id: 116,
      subWeaponId: 14,
      specialWeaponId: 15,
    },
    {
      name: 'L3リールガンD ',
      name_en: 'L-3 Nozzlenose D ',
      id: 165,
      subWeaponId: 13,
      specialWeaponId: 10,
    },
    {
      name: 'L3リールガンベッチュー ',
      name_en: 'Kensa L-3 Nozzlenose ',
      id: 208,
      subWeaponId: 19,
      specialWeaponId: 23,
    },
    {
      name: '.96ガロン ',
      name_en: '.96 Gal ',
      id: 119,
      subWeaponId: 20,
      specialWeaponId: 12,
    },
    {
      name: '.96ガロンデコ ',
      name_en: '.96 Gal Deco ',
      id: 169,
      subWeaponId: 19,
      specialWeaponId: 11,
    },
    {
      name: 'H3リールガン ',
      name_en: 'H-3 Nozzlenose ',
      id: 127,
      subWeaponId: 18,
      specialWeaponId: 8,
    },
    {
      name: 'H3リールガンD ',
      name_en: 'H-3 Nozzlenose D ',
      id: 175,
      subWeaponId: 12,
      specialWeaponId: 12,
    },
    {
      name: 'H3リールガンチェリー ',
      name_en: 'TBC ',
      id: 223,
      subWeaponId: 19,
      specialWeaponId: 16,
    },
    {
      name: 'ボールドマーカー ',
      name_en: 'Sploosh-o-matic ',
      id: 140,
      subWeaponId: 14,
      specialWeaponId: 11,
    },
    {
      name: 'ボールドマーカーネオ ',
      name_en: 'Neo Sploosh-o-matic ',
      id: 174,
      subWeaponId: 21,
      specialWeaponId: 8,
    },
    {
      name: 'ボールドマーカー7 ',
      name_en: 'TBC ',
      id: 219,
      subWeaponId: 11,
      specialWeaponId: 23,
    },
    {
      name: 'ボトルガイザー ',
      name_en: 'Squeezer ',
      id: 162,
      subWeaponId: 19,
      specialWeaponId: 9,
    },
    {
      name: 'ボトルガイザーフォイル ',
      name_en: 'Foil Squeezer ',
      id: 182,
      subWeaponId: 11,
      specialWeaponId: 16,
    },
    {
      name: 'ホットブラスター ',
      name_en: 'Blaster ',
      id: 98,
      subWeaponId: 17,
      specialWeaponId: 11,
    },
    {
      name: 'ホットブラスターカスタム ',
      name_en: 'Custom Blaster ',
      id: 125,
      subWeaponId: 15,
      specialWeaponId: 10,
    },
    {
      name: 'ヒーローブラスター レプリカ ',
      name_en: 'Hero Blaster Replica ',
      id: 136,
      subWeaponId: 17,
      specialWeaponId: 11,
    },
    {
      name: 'ラピッドブラスター ',
      name_en: 'Rapid Blaster ',
      id: 111,
      subWeaponId: 16,
      specialWeaponId: 17,
    },
    {
      name: 'ラピッドブラスターデコ ',
      name_en: 'Rapid Blaster Deco ',
      id: 168,
      subWeaponId: 12,
      specialWeaponId: 10,
    },
    {
      name: 'ラピッドブラスターベッチュー ',
      name_en: 'Kensa Rapid Blaster ',
      id: 212,
      subWeaponId: 23,
      specialWeaponId: 15,
    },
    {
      name: 'ノヴァブラスター ',
      name_en: 'Luna Blaster ',
      id: 117,
      subWeaponId: 11,
      specialWeaponId: 15,
    },
    {
      name: 'ノヴァブラスターネオ ',
      name_en: 'Luna Blaster Neo ',
      id: 172,
      subWeaponId: 16,
      specialWeaponId: 18,
    },
    {
      name: 'ノヴァブラスターベッチュー ',
      name_en: 'Kensa Luna Blaster ',
      id: 204,
      subWeaponId: 22,
      specialWeaponId: 14,
    },
    {
      name: 'クラッシュブラスター ',
      name_en: 'Clash Blaster ',
      id: 128,
      subWeaponId: 11,
      specialWeaponId: 9,
    },
    {
      name: 'クラッシュブラスターネオ ',
      name_en: 'Clash Blaster Neo ',
      id: 178,
      subWeaponId: 14,
      specialWeaponId: 8,
    },
    {
      name: 'Rブラスターエリート ',
      name_en: 'Rapid Blaster Pro ',
      id: 148,
      subWeaponId: 17,
      specialWeaponId: 14,
    },
    {
      name: 'Rブラスターエリートデコ ',
      name_en: 'Rapid Blaster Pro Deco ',
      id: 185,
      subWeaponId: 19,
      specialWeaponId: 12,
    },
    {
      name: 'ロングブラスター ',
      name_en: 'Range Blaster ',
      id: 153,
      subWeaponId: 12,
      specialWeaponId: 14,
    },
    {
      name: 'ロングブラスターカスタム ',
      name_en: 'Custom Range Blaster ',
      id: 180,
      subWeaponId: 14,
      specialWeaponId: 16,
    },
    {
      name: 'ロングブラスターネクロ ',
      name_en: 'TBC ',
      id: 222,
      subWeaponId: 13,
      specialWeaponId: 8,
    },
    {
      name: 'スプラローラー ',
      name_en: 'Splat Roller ',
      id: 93,
      subWeaponId: 14,
      specialWeaponId: 11,
    },
    {
      name: 'スプラローラーコラボ ',
      name_en: 'Krak-On Splat Roller ',
      id: 110,
      subWeaponId: 21,
      specialWeaponId: 15,
    },
    {
      name: 'ヒーローローラー レプリカ ',
      name_en: 'Hero Roller Replica ',
      id: 133,
      subWeaponId: 14,
      specialWeaponId: 11,
    },
    {
      name: 'スプラローラーベッチュー ',
      name_en: 'Kensa Splat Roller ',
      id: 199,
      subWeaponId: 11,
      specialWeaponId: 16,
    },
    {
      name: 'ダイナモローラー ',
      name_en: 'Dynamo Roller ',
      id: 101,
      subWeaponId: 16,
      specialWeaponId: 9,
    },
    {
      name: 'ダイナモローラーテスラ ',
      name_en: 'Gold Dynamo Roller ',
      id: 154,
      subWeaponId: 11,
      specialWeaponId: 12,
    },
    {
      name: 'ダイナモローラーベッチュー ',
      name_en: 'Kensa Dynamo Roller ',
      id: 205,
      subWeaponId: 20,
      specialWeaponId: 22,
    },
    {
      name: 'カーボンローラー ',
      name_en: 'Carbon Roller ',
      id: 107,
      subWeaponId: 15,
      specialWeaponId: 14,
    },
    {
      name: 'カーボンローラーデコ ',
      name_en: 'Carbon Roller Deco ',
      id: 186,
      subWeaponId: 13,
      specialWeaponId: 20,
    },
    {
      name: 'ヴァリアブルローラー ',
      name_en: 'Flingza Roller ',
      id: 122,
      subWeaponId: 19,
      specialWeaponId: 17,
    },
    {
      name: 'ヴァリアブルローラーフォイル ',
      name_en: 'Foil Flingza Roller ',
      id: 157,
      subWeaponId: 12,
      specialWeaponId: 8,
    },
    {
      name: 'ホクサイ ',
      name_en: 'Octobrush ',
      id: 99,
      subWeaponId: 15,
      specialWeaponId: 10,
    },
    {
      name: 'ヒーローブラシ レプリカ ',
      name_en: 'Herobrush Replica ',
      id: 139,
      subWeaponId: 15,
      specialWeaponId: 10,
    },
    {
      name: 'ホクサイ・ヒュー ',
      name_en: 'Octobrush Nouveau ',
      id: 164,
      subWeaponId: 21,
      specialWeaponId: 8,
    },
    {
      name: 'ホクサイベッチュー ',
      name_en: 'Kensa Octobrush ',
      id: 209,
      subWeaponId: 12,
      specialWeaponId: 23,
    },
    {
      name: 'パブロ ',
      name_en: 'Inkbrush ',
      id: 130,
      subWeaponId: 11,
      specialWeaponId: 11,
    },
    {
      name: 'パブロ・ヒュー ',
      name_en: 'Inkbrush Nouveau ',
      id: 156,
      subWeaponId: 16,
      specialWeaponId: 15,
    },
    {
      name: 'パーマネント・パブロ ',
      name_en: 'TBC ',
      id: 224,
      subWeaponId: 20,
      specialWeaponId: 12,
    },
    {
      name: 'スプラチャージャー ',
      name_en: 'Splat Charger ',
      id: 94,
      subWeaponId: 11,
      specialWeaponId: 9,
    },
    {
      name: 'スプラスコープ ',
      name_en: 'Splatterscope ',
      id: 103,
      subWeaponId: 11,
      specialWeaponId: 9,
    },
    {
      name: 'スプラチャージャーコラボ ',
      name_en: 'Firefin Splat Charger ',
      id: 114,
      subWeaponId: 19,
      specialWeaponId: 18,
    },
    {
      name: 'スプラスコープコラボ ',
      name_en: 'Firefin Splatterscope ',
      id: 123,
      subWeaponId: 19,
      specialWeaponId: 18,
    },
    {
      name: 'ヒーローチャージャー レプリカ ',
      name_en: 'Hero Charger Replica ',
      id: 134,
      subWeaponId: 11,
      specialWeaponId: 9,
    },
    {
      name: 'スプラチャージャーベッチュー ',
      name_en: 'Kensa Charger ',
      id: 200,
      subWeaponId: 20,
      specialWeaponId: 15,
    },
    {
      name: 'スプラスコープベッチュー ',
      name_en: 'Kensa Splatterscope ',
      id: 201,
      subWeaponId: 20,
      specialWeaponId: 15,
    },
    {
      name: 'リッター4K ',
      name_en: 'E-liter 4K ',
      id: 118,
      subWeaponId: 16,
      specialWeaponId: 14,
    },
    {
      name: '4Kスコープ ',
      name_en: 'E-liter 4K Scope ',
      id: 129,
      subWeaponId: 16,
      specialWeaponId: 14,
    },
    {
      name: 'リッター4Kカスタム ',
      name_en: 'Custom E-liter 4K ',
      id: 151,
      subWeaponId: 21,
      specialWeaponId: 16,
    },
    {
      name: '4Kスコープカスタム ',
      name_en: 'Custom E-liter 4K Scope ',
      id: 152,
      subWeaponId: 21,
      specialWeaponId: 16,
    },
    {
      name: 'ソイチューバー ',
      name_en: 'Goo Tuber ',
      id: 120,
      subWeaponId: 12,
      specialWeaponId: 11,
    },
    {
      name: 'ソイチューバーカスタム ',
      name_en: 'Custom Goo Tuber ',
      id: 170,
      subWeaponId: 14,
      specialWeaponId: 10,
    },
    {
      name: 'スクイックリンα ',
      name_en: 'Classic Squiffer ',
      id: 143,
      subWeaponId: 18,
      specialWeaponId: 12,
    },
    {
      name: 'スクイックリンβ ',
      name_en: 'New Squiffer ',
      id: 183,
      subWeaponId: 15,
      specialWeaponId: 15,
    },
    {
      name: 'スクイックリンγ ',
      name_en: 'TBC ',
      id: 225,
      subWeaponId: 12,
      specialWeaponId: 10,
    },
    {
      name: '14式竹筒銃・甲 ',
      name_en: 'Bamboozler 14 Mk I ',
      id: 150,
      subWeaponId: 14,
      specialWeaponId: 8,
    },
    {
      name: '14式竹筒銃・乙 ',
      name_en: 'Bamboozler 14 Mk II ',
      id: 190,
      subWeaponId: 17,
      specialWeaponId: 21,
    },
    {
      name: '14式竹筒銃・丙 ',
      name_en: 'TBC ',
      id: 226,
      subWeaponId: 22,
      specialWeaponId: 16,
    },
    {
      name: 'バケットスロッシャー ',
      name_en: 'Slosher ',
      id: 96,
      subWeaponId: 12,
      specialWeaponId: 8,
    },
    {
      name: 'ヒーロースロッシャー レプリカ ',
      name_en: 'Hero Slosher Replica ',
      id: 137,
      subWeaponId: 12,
      specialWeaponId: 8,
    },
    {
      name: 'バケットスロッシャーデコ ',
      name_en: 'Slosher Deco ',
      id: 161,
      subWeaponId: 20,
      specialWeaponId: 15,
    },
    {
      name: 'バケットスロッシャーソーダ ',
      name_en: 'TBC ',
      id: 227,
      subWeaponId: 11,
      specialWeaponId: 21,
    },
    {
      name: 'ヒッセン ',
      name_en: 'Tri-Slosher ',
      id: 113,
      subWeaponId: 13,
      specialWeaponId: 12,
    },
    {
      name: 'ヒッセン・ヒュー ',
      name_en: 'Tri-Slosher Nouveau ',
      id: 179,
      subWeaponId: 11,
      specialWeaponId: 14,
    },
    {
      name: 'スクリュースロッシャー ',
      name_en: 'Sloshing Machine ',
      id: 144,
      subWeaponId: 15,
      specialWeaponId: 9,
    },
    {
      name: 'スクリュースロッシャーネオ ',
      name_en: 'Sloshing Machine Neo ',
      id: 171,
      subWeaponId: 18,
      specialWeaponId: 17,
    },
    {
      name: 'スクリュースロッシャーベッチュー ',
      name_en: 'Kensa Sloshing Machine ',
      id: 206,
      subWeaponId: 22,
      specialWeaponId: 11,
    },
    {
      name: 'エクスプロッシャー ',
      name_en: 'Explosher ',
      id: 191,
      subWeaponId: 20,
      specialWeaponId: 16,
    },
    {
      name: 'エクスプロッシャーカスタム ',
      name_en: 'Custom Explosher ',
      id: 214,
      subWeaponId: 18,
      specialWeaponId: 15,
    },
    {
      name: 'オーバーフロッシャー ',
      name_en: 'Bloblobber ',
      id: 194,
      subWeaponId: 19,
      specialWeaponId: 14,
    },
    {
      name: 'オーバーフロッシャーデコ ',
      name_en: 'Bloblobber Deco ',
      id: 213,
      subWeaponId: 20,
      specialWeaponId: 18,
    },
    {
      name: 'バレルスピナー ',
      name_en: 'Heavy Splatling ',
      id: 97,
      subWeaponId: 20,
      specialWeaponId: 9,
    },
    {
      name: 'ヒーロースピナー レプリカ ',
      name_en: 'Hero Splatling Replica ',
      id: 138,
      subWeaponId: 20,
      specialWeaponId: 9,
    },
    {
      name: 'バレルスピナーデコ ',
      name_en: 'Heavy Splatling Deco ',
      id: 147,
      subWeaponId: 19,
      specialWeaponId: 16,
    },
    {
      name: 'バレルスピナーリミックス ',
      name_en: 'TBC ',
      id: 228,
      subWeaponId: 18,
      specialWeaponId: 22,
    },
    {
      name: 'スプラスピナー ',
      name_en: 'Mini Splatling ',
      id: 121,
      subWeaponId: 13,
      specialWeaponId: 8,
    },
    {
      name: 'スプラスピナーコラボ ',
      name_en: 'Zink Mini Splatling ',
      id: 176,
      subWeaponId: 14,
      specialWeaponId: 14,
    },
    {
      name: 'スプラスピナーベッチュー ',
      name_en: 'Kensa Mini Splatling ',
      id: 215,
      subWeaponId: 17,
      specialWeaponId: 23,
    },
    {
      name: 'ハイドラント ',
      name_en: 'Hydra Splatling ',
      id: 158,
      subWeaponId: 15,
      specialWeaponId: 11,
    },
    {
      name: 'ハイドラントカスタム ',
      name_en: 'Custom Hydra Splatling ',
      id: 195,
      subWeaponId: 16,
      specialWeaponId: 12,
    },
    {
      name: 'クーゲルシュライバー ',
      name_en: 'Ballpoint Splatling ',
      id: 192,
      subWeaponId: 17,
      specialWeaponId: 10,
    },
    {
      name: 'クーゲルシュライバー・ヒュー ',
      name_en: 'Ballpoint Splatling Nouveau ',
      id: 216,
      subWeaponId: 21,
      specialWeaponId: 14,
    },
    {
      name: 'ノーチラス47 ',
      name_en: 'Nautilus 47 ',
      id: 196,
      subWeaponId: 18,
      specialWeaponId: 15,
    },
    {
      name: 'ノーチラス79 ',
      name_en: 'Nautilus 79 ',
      id: 217,
      subWeaponId: 12,
      specialWeaponId: 10,
    },
    {
      name: 'スプラマニューバー ',
      name_en: 'Splat Dualies ',
      id: 95,
      subWeaponId: 13,
      specialWeaponId: 8,
    },
    {
      name: 'スプラマニューバーコラボ ',
      name_en: 'Enperry Splat Dualies ',
      id: 109,
      subWeaponId: 14,
      specialWeaponId: 10,
    },
    {
      name: 'ヒーローマニューバー レプリカ ',
      name_en: 'Hero Dualie Replicas ',
      id: 135,
      subWeaponId: 13,
      specialWeaponId: 8,
    },
    {
      name: 'スプラマニューバーベッチュー ',
      name_en: 'Kensa Splat Dualies ',
      id: 202,
      subWeaponId: 12,
      specialWeaponId: 15,
    },
    {
      name: 'スパッタリー ',
      name_en: 'Dapple Dualies ',
      id: 124,
      subWeaponId: 21,
      specialWeaponId: 18,
    },
    {
      name: 'スパッタリー・ヒュー ',
      name_en: 'Dapple Dualies Nouveau ',
      id: 166,
      subWeaponId: 17,
      specialWeaponId: 14,
    },
    {
      name: 'スパッタリークリア ',
      name_en: 'TBC ',
      id: 229,
      subWeaponId: 23,
      specialWeaponId: 11,
    },
    {
      name: 'デュアルスイーパー ',
      name_en: 'Dualie Squelchers ',
      id: 131,
      subWeaponId: 18,
      specialWeaponId: 8,
    },
    {
      name: 'デュアルスイーパーカスタム ',
      name_en: 'Custom Dualie Squelchers ',
      id: 187,
      subWeaponId: 11,
      specialWeaponId: 14,
    },
    {
      name: 'ケルビン525 ',
      name_en: 'Glooga Dualies ',
      id: 159,
      subWeaponId: 16,
      specialWeaponId: 10,
    },
    {
      name: 'ケルビン525デコ ',
      name_en: 'Glooga Dualies Deco ',
      id: 184,
      subWeaponId: 19,
      specialWeaponId: 15,
    },
    {
      name: 'ケルビン525ベッチュー ',
      name_en: 'Kensa Glooga Dualies ',
      id: 218,
      subWeaponId: 22,
      specialWeaponId: 12,
    },
    {
      name: 'クアッドホッパーブラック ',
      name_en: 'Dark Tetra Dualies ',
      id: 173,
      subWeaponId: 15,
      specialWeaponId: 11,
    },
    {
      name: 'クアッドホッパーホワイト ',
      name_en: 'Light Tetra Dualies ',
      id: 197,
      subWeaponId: 20,
      specialWeaponId: 20,
    },
    {
      name: 'パラシェルター ',
      name_en: 'Splat Brella ',
      id: 141,
      subWeaponId: 20,
      specialWeaponId: 14,
    },
    {
      name: 'ヒーローシェルター レプリカ ',
      name_en: 'Hero Brella Replica ',
      id: 142,
      subWeaponId: 20,
      specialWeaponId: 14,
    },
    {
      name: 'パラシェルターソレーラ ',
      name_en: 'Sorella Brella ',
      id: 177,
      subWeaponId: 15,
      specialWeaponId: 17,
    },
    {
      name: 'キャンピングシェルター ',
      name_en: 'Tenta Brella ',
      id: 149,
      subWeaponId: 21,
      specialWeaponId: 16,
    },
    {
      name: 'キャンピングシェルターソレーラ ',
      name_en: 'Tenta Sorella Brella ',
      id: 193,
      subWeaponId: 19,
      specialWeaponId: 19,
    },
    {
      name: 'キャンピングシェルターカーモ ',
      name_en: 'TBC ',
      id: 230,
      subWeaponId: 16,
      specialWeaponId: 23,
    },
    {
      name: 'スパイガジェット ',
      name_en: 'Undercover Brella ',
      id: 163,
      subWeaponId: 16,
      specialWeaponId: 11,
    },
    {
      name: 'スパイガジェットソレーラ ',
      name_en: 'Undercover Sorella Brella ',
      id: 188,
      subWeaponId: 11,
      specialWeaponId: 15,
    },
    {
      name: 'スパイガジェットベッチュー ',
      name_en: 'Kensa Undercover Brella ',
      id: 210,
      subWeaponId: 23,
      specialWeaponId: 12,
    },
];
